//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameDev.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharacterAttribute
    {
        public System.Guid CharacterAttributeID { get; set; }
        public System.Guid CharacterID { get; set; }
        public System.Guid AttributeID { get; set; }
        public Nullable<int> Value { get; set; }
    
        public virtual Attribute Attribute { get; set; }
    }
}
