//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameDev.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        public System.Guid CharacterID { get; set; }
        public System.Guid ClassID { get; set; }
        public System.Guid UserID { get; set; }
        public int Level { get; set; }
        public int Gold { get; set; }
        public int Gems { get; set; }
        public Nullable<System.Guid> GuildID { get; set; }
        public int Energy { get; set; }
    
        public virtual User User { get; set; }
    }
}
