//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameDev.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassAttribute
    {
        public System.Guid ClassAttributeID { get; set; }
        public System.Guid ClassID { get; set; }
        public System.Guid AttributeID { get; set; }
        public Nullable<int> InitialValue { get; set; }
        public Nullable<int> IncrementValue { get; set; }
    
        public virtual Attribute Attribute { get; set; }
        public virtual Class Class { get; set; }
    }
}
